apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-deployment
  labels:
    app: fitness-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-tracker
  template:
    metadata:
      labels:
        app: fitness-tracker
    spec:
      containers:
      - name: fitness-tracker
        image: fitness-tracker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
