kind: Service
apiVersion: v1
metadata:
  name: fitness-tracker-service
spec:
  type: NodePort
  selector:
    app: fitness-tracker

  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
