name:                fitness-tracker
version:             0.1.0.0
github:              "githubuser/fitness-tracker"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fitness-tracker#readme>

dependencies:
- aeson >= 1.5.6.0
- base >= 4.7 && < 5
- servant >= 0.18.3
- servant-server >= 0.18.3
- sqlite-simple >= 0.4.18.0
- text
- time
- wai >= 3.2.3
- warp >= 3.3.17

library:
  source-dirs: src

executables:
  fitness-tracker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fitness-tracker

tests:
  fitness-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fitness-tracker
